--------------------------------------------------------------------------------
-- ETL DEL SA
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PG_ETL_SA AS
   PROCEDURE CARGA_CLIENTE;
   PROCEDURE CARGA_PRESTAMO;
   PROCEDURE CARGA_DATOS;
END PG_ETL_SA;
/

CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS
   PROCEDURE CARGA_CLIENTE AS
   BEGIN
      INSERT INTO SISFINANZAS_SA.SA_CLIENTE(CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO)
      SELECT CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO
        FROM SISFINANZAS_ER.CLIENTE
       WHERE CTE_ID NOT IN (SELECT CTE_ID FROM SISFINANZAS_SA.SA_CLIENTE);
   END CARGA_CLIENTE;
   PROCEDURE CARGA_PRESTAMO AS
   BEGIN
      INSERT INTO SISFINANZAS_SA.SA_PRESTAMO(PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES)
      SELECT PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES
        FROM SISFINANZAS_ER.PRESTAMO
       WHERE PST_ID NOT IN (SELECT PST_ID FROM SISFINANZAS_SA.SA_PRESTAMO);
   END CARGA_PRESTAMO;
   PROCEDURE CARGA_DATOS AS
   BEGIN
     CARGA_CLIENTE;
     CARGA_PRESTAMO;
     COMMIT;
   END CARGA_DATOS;
END PG_ETL_SA;
/

EXECUTE PG_ETL_SA.CARGA_DATOS;