CREATE TABLE ESTUDIANTES(
    EST_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    EST_NOMBRE VARCHAR2(50) NOT NULL,
    EST_EDAD NUMBER CHECK(EST_EDAD BETWEEN 16 AND 30),
    EST_CARRERA VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ESTUDIANTES PRIMARY KEY(EST_ID)
);

CREATE TABLE CURSOS(
    CRS_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    CRS_NOMBRE_CURSO VARCHAR2(40) NOT NULL,
    CRS_CREDITOS NUMBER DEFAULT 3,
    CONSTRAINT PK_CURSOS PRIMARY KEY(CRS_ID)
);

CREATE TABLE MATICULAS(
    MTC_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    MTC_EST_ID NUMBER NOT NULL,
    MTC_CRS_ID NUMBER NOT NULL,
    MTC_FECHA_MATRICULA DATE DEFAULT CURRENT_DATE,
    MTC_NOTA_FINAL NUMBER CHECK(MTC_NOTA_FINAL BETWEEN 0 AND 5),
    CONSTRAINT PK_MATRICULA PRIMARY KEY(MTC_ID),
    CONSTRAINT FK_MTC_ESTUDIANTES FOREIGN KEY(MTC_EST_ID) REFERENCES ESTUDIANTES(EST_ID),
    CONSTRAINT FK_MTC_CURSOS FOREIGN KEY(MTC_CRS_ID) REFERENCES CURSOS(CRS_ID)
);

INSERT INTO ESTUDIANTES (EST_NOMBRE, EST_EDAD, EST_CARRERA) VALUES ('Juan Pérez', 20, 'Ingeniería');
INSERT INTO ESTUDIANTES (EST_NOMBRE, EST_EDAD, EST_CARRERA) VALUES ('María López', 18, 'Derecho');
INSERT INTO ESTUDIANTES (EST_NOMBRE, EST_EDAD, EST_CARRERA) VALUES ('Carlos Ruiz', 25, 'Medicina');
INSERT INTO ESTUDIANTES (EST_NOMBRE, EST_EDAD, EST_CARRERA) VALUES ('Ana García', 19, 'Arquitectura');

INSERT INTO CURSOS (CRS_NOMBRE_CURSO, CRS_CREDITOS) VALUES ('Cálculo Diferencial', 4);
INSERT INTO CURSOS (CRS_NOMBRE_CURSO, CRS_CREDITOS) VALUES ('Programación SQL', 5);
INSERT INTO CURSOS (CRS_NOMBRE_CURSO) VALUES ('Ética Profesional');
INSERT INTO CURSOS (CRS_NOMBRE_CURSO, CRS_CREDITOS) VALUES ('Base de Datos II', 4);

-- Estudiante 1 se matricula en Curso 1 con nota 4
INSERT INTO MATICULAS (MTC_EST_ID, MTC_CRS_ID, MTC_NOTA_FINAL) VALUES (1, 1, 4);

-- Estudiante 2 se matricula en Curso 2 con nota 5
INSERT INTO MATICULAS (MTC_EST_ID, MTC_CRS_ID, MTC_NOTA_FINAL) VALUES (2, 2, 5);

-- Estudiante 3 se matricula en Curso 1 con nota 3 (Fecha por defecto)
INSERT INTO MATICULAS (MTC_EST_ID, MTC_CRS_ID, MTC_NOTA_FINAL) VALUES (3, 1, 3);

-- Estudiante 1 se matricula en Curso 3 con nota 2
INSERT INTO MATICULAS (MTC_EST_ID, MTC_CRS_ID, MTC_NOTA_FINAL) VALUES (1, 3, 2);

SELECT E.EST_CARRERA CARRERA
FROM ESTUDIANTES E
WHERE E.EST_CARRERA = 'Ingeniería'
ORDER BY E.EST_CARRERA DESC;

SELECT E.EST_NOMBRE NOMBRE_ESTUDIANTE,
       M.MTC_FECHA_MATRICULA FECHA_MATRICULA,
       M.MTC_NOTA_FINAL NOTA_FINAL
FROM ESTUDIANTES E INNER JOIN MATICULAS M ON E.EST_ID = M.MTC_EST_ID; -- Le puse mal en nombre a la tabla MATRICULAS perdon

SELECT C.CRS_NOMBRE_CURSO NOMBRE_CURSO,
       COUNT(M.MTC_ID) NUMERO_MATRICULA
FROM CURSOS C LEFT JOIN MATICULAS M ON C.CRS_ID = M.MTC_CRS_ID
GROUP BY C.CRS_NOMBRE_CURSO;

SELECT E.EST_CARRERA CARRERA,
       AVG(E.EST_EDAD) PROM_EDAD_ESTUDIANTES
FROM ESTUDIANTES E
GROUP BY E.EST_CARRERA;
-- HAVING COUNT(E.EST_ID) > 2; 
-- Se comenta para que la consulta si de un resultado

SELECT E.EST_NOMBRE ESTUDIANTE,
       M.MTC_NOTA_FINAL CALIFICACION
FROM ESTUDIANTES E INNER JOIN MATICULAS M ON E.EST_ID = M.MTC_EST_ID
WHERE M.MTC_NOTA_FINAL > 3;

SELECT E.EST_CARRERA CARRERA,
       AVG(E.EST_EDAD) PROM_EDAD 
FROM ESTUDIANTES E
GROUP BY E.EST_CARRERA
HAVING AVG(EST_EDAD) > 22;


