CREATE TABLE PLANILLA (
EMP_ID           
INTEGER NOT NULL PRIMARY KEY,
EMP_NOMBRE       
VARCHAR2(40) NOT NULL,
EMP_DEPARTAMENTO VARCHAR2(40) NOT NULL,
EMP_SALARIO DECIMAL(11,2) NOT NULL
);


INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7481,'Empleado 7481',1,551000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7482,'Empleado 7482',3,634000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7483,'Empleado 7483',5,766000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7484,'Empleado 7484',1,710000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7485,'Empleado 7485',1,551000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7486,'Empleado 7486',1,551000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7487,'Empleado 7487',2,639000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7488,'Empleado 7488',3,777000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7489,'Empleado 7489',4,782000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7490,'Empleado 7490',1,751000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7491,'Empleado 7491',5,655000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7492,'Empleado 7492',5,726000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7493,'Empleado 7493',1,749000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7494,'Empleado 7494',4,629000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7495,'Empleado 7495',3,643000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7496,'Empleado 7496',5,786000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7497,'Empleado 7497',3,754000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7498,'Empleado 7498',3,602000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7499,'Empleado 7499',1,796000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7500,'Empleado 7500',3,520000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7501,'Empleado 7501',2,574000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7502,'Empleado 7502',3,660000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7503,'Empleado 7503',4,700000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7504,'Empleado 7504',4,672000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7505,'Empleado 7505',3,673000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7506,'Empleado 7506',2,726000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7507,'Empleado 7507',1,596000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7508,'Empleado 7508',4,766000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7509,'Empleado 7509',3,704000);
INSERT INTO PLANILLA(EMP_ID, EMP_NOMBRE, EMP_DEPARTAMENTO, EMP_SALARIO) VALUES (7510,'Empleado 7510',5,655000);
COMMIT;





--------------------------------------------------------------------------------
-- Ejercicio 1
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       FIRST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO)
       AS PRIMER_SALARIO FROM PLANILLA;
       
--------------------------------------------------------------------------------
-- Ejercicio 2
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       LEAD(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO)
       AS SIGUIENTE_SALARIO
       FROM PLANILLA;



--------------------------------------------------------------------------------
-- Ejercicio 3
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       LAST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO
       ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
       AS ULTIMO_SALARIO
       FROM PLANILLA;
       

--------------------------------------------------------------------------------
-- Ejercicio 4
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       FIRST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO)
       AS PRIMER_SALARIO,
       (EMP_SALARIO - FIRST_VALUE(EMP_SALARIO) OVER (PARTITION BY EMP_DEPARTAMENTO
       ORDER BY EMP_SALARIO))
       AS DIFERENCIA_PRIMER_SALARIO
       FROM PLANILLA;

--------------------------------------------------------------------------------
-- Ejercicio 5
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       LAST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO
       ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
       AS ULTIMO_SALARIO,
       (EMP_SALARIO - LAST_VALUE(EMP_SALARIO) OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO
       ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING))
       AS DEFERENCIA_ULTIMO_MAYOR
       FROM PLANILLA;
       
--------------------------------------------------------------------------------
-- Ejercicio 6
--------------------------------------------------------------------------------

SELECT EMP_ID,
       EMP_NOMBRE,
       EMP_DEPARTAMENTO,
       EMP_SALARIO,
       FIRST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO)
       AS PRIMER_SALARIO,
       LEAD(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO)
       AS SIGUIENTE_SALARIO,
       LAST_VALUE(EMP_SALARIO) IGNORE NULLS
       OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO
       ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
       AS ULTIMO_SALARIO,
       (EMP_SALARIO - FIRST_VALUE(EMP_SALARIO) OVER (PARTITION BY EMP_DEPARTAMENTO
       ORDER BY EMP_SALARIO))
       AS DIFERENCIA_PRIMER_SALARIO,
       (EMP_SALARIO - LAST_VALUE(EMP_SALARIO) OVER (PARTITION BY EMP_DEPARTAMENTO ORDER BY EMP_SALARIO
       ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING))
       AS DEFERENCIA_ULTIMO_MAYOR
       FROM PLANILLA;
       
       
       
       






