--------------------------------------------------------------------------------
-- CREAR TABLAS
--------------------------------------------------------------------------------


-- TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    PUESTO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY(ID_EMPLEADO)
);


-- TABLA CLIENTES
CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE)
);


-- TABLA DESTINOS
CREATE TABLE DESTINOS(
    ID_DESTINO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    PAIS VARCHAR2(50) NOT NULL,
    CIUDAD VARCHAR2(50) NOT NULL,
    COSTO_ESTIMADO NUMBER NOT NULL,
    CONSTRAINT PK_DESTINOS PRIMARY KEY(ID_DESTINO)
);


--TABLA RESERVAS
CREATE TABLE RESERVAS(
    ID_RESERVA NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_DESTINO NUMBER NOT NULL,
    FECHA_RESERVA DATE DEFAULT CURRENT_DATE,
    COSTO_RESERVA NUMBER NOT NULL,
    CONSTRAINT PK_RESERVAS PRIMARY KEY(ID_RESERVA),
    CONSTRAINT FK_EMP_RESERVAS FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_CLI_RESERVAS FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_DES_RESERVAS FOREIGN KEY(ID_DESTINO) REFERENCES DESTINOS(ID_DESTINO)
);

--------------------------------------------------------------------------------
-- INSERTAR DATOS
--------------------------------------------------------------------------------


-- INSERTAR EMPLEADOS
INSERT INTO EMPLEADOS (NOMBRE,PUESTO)VALUES('Juan Perez', 'Gerente');
INSERT INTO EMPLEADOS (NOMBRE,PUESTO)VALUES('MariaLopez', 'Agente de Ventas');
INSERT INTO EMPLEADOS (NOMBRE,PUESTO)VALUES('LuisGarcía', 'Agente de Ventas');


-- INSERTAR CLIENTES
INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES('Ana Castillo', 'ana@example.com');
INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES('Carlos Mora', 'carlos@example.com');


-- INSERTAR DESTINOS
INSERT INTO DESTINOS (PAIS, CIUDAD, COSTO_ESTIMADO)VALUES ('Costa Rica', 'San José', 500);
INSERT INTO DESTINOS (PAIS, CIUDAD, COSTO_ESTIMADO)VALUES ('España', 'Madrid', 1200);


-- INSERTAR RESERVAS
INSERT INTO RESERVAS (ID_EMPLEADO, ID_CLIENTE, ID_DESTINO, FECHA_RESERVA, COSTO_RESERVA)
VALUES (1, 1, 1, SYSDATE, 550);
INSERT INTO RESERVAS (ID_EMPLEADO, ID_CLIENTE, ID_DESTINO, FECHA_RESERVA, COSTO_RESERVA)
VALUES (2, 2, 2, SYSDATE, 1300);


--------------------------------------------------------------------------------
-- CREAR ROLES
--------------------------------------------------------------------------------


CREATE ROLE C##ROL_GERENTE;
CREATE ROLE C##ROL_SUPERVISOR;
CREATE ROLE C##ROL_VENTAS;


--------------------------------------------------------------------------------
-- PERMISOS DE ROLES
--------------------------------------------------------------------------------


-- ROL_GERENTE
GRANT SELECT, INSERT, UPDATE, DELETE ON RESERVAS TO C##ROL_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADOS TO C##ROL_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES TO C##ROL_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESTINOS TO C##ROL_GERENTE;

-- ROL_SUPERVISOR
GRANT SELECT, INSERT, UPDATE, DELETE ON RESERVAS TO C##ROL_SUPERVISOR;

-- ROL_VENTAS
GRANT SELECT ON DESTINOS TO C##ROL_VENTAS;
GRANT SELECT, INSERT ON RESERVAS TO C##ROL_VENTAS;


--------------------------------------------------------------------------------
-- CREAR USUARIOS Y ASIGNAR ROLES
--------------------------------------------------------------------------------

-- USUARIO Y ROL DE GERENTE
CREATE USER C##GERENTE IDENTIFIED BY Oracle01;
GRANT C##ROL_GERENTE TO C##GERENTE;

-- USUARIO Y ROL DE SUPERVISOR
CREATE USER C##SUPERVISOR IDENTIFIED BY Oracle01;
GRANT C##ROL_SUPERVISOR TO C##SUPERVISOR;

-- USUARIO Y ROL DE VENTAS
CREATE USER C##VENTAS IDENTIFIED BY Oracle01;
GRANT C##ROL_VENTAS TO C##VENTAS;









