--------------------------------------------------------------------------------
-- CREACION DE TABLAS MODELO RELACIONAL.
-- SE CONECTA CON EL USUARIO CREADO PARA ER.
--------------------------------------------------------------------------------

CREATE TABLE CATEGORIAS(
    CTG_ID INTEGER NOT NULL CONSTRAINT PK_CTG_ID PRIMARY KEY,
    CTG_DESCRIPCION VARCHAR2(30) NOT NULL
);

CREATE TABLE PRODUCTOS(
    PRD_ID INTEGER NOT NULL CONSTRAINT PK_PRD_ID PRIMARY KEY,
    PRD_CTG_ID INTEGER NOT NULL,
    PRD_NOMBRE_PRODUCTO VARCHAR2(50) NOT NULL,
    PRD_PRECIO_BASE DECIMAL(20,2) NOT NULL,
    CONSTRAINT FK_PRD_CTG FOREIGN KEY(PRD_CTG_ID) REFERENCES CATEGORIAS(CTG_ID)
);

CREATE TABLE CIUDADES(
    CDD_ID INTEGER NOT NULL CONSTRAINT PK_CDD_ID PRIMARY KEY,
    CDD_NOMBRE_CIUDAD VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    CLI_ID INTEGER NOT NULL CONSTRAINT PK_CLI_ID PRIMARY KEY,
    CLI_CDD_ID INTEGER NOT NULL,
    CLI_NOMBRE VARCHAR2(100) NOT NULL,
    CLI_APELLIDO VARCHAR2(100) NOT NULL,
    CLI_CONTACTO VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CLI_CDD FOREIGN KEY(CLI_CDD_ID) REFERENCES CIUDADES(CDD_ID)
);

CREATE TABLE SUCURSALES(
    SCS_ID INTEGER NOT NULL CONSTRAINT PK_SCS_ID PRIMARY KEY,
    SCS_CDD_ID INTEGER NOT NULL,
    SCS_NOMBRE_SUCURSAL VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_SCS_CDD FOREIGN KEY(SCS_CDD_ID) REFERENCES CIUDADES(CDD_ID) 
);

CREATE TABLE VENDEDORES(
    VND_ID INTEGER NOT NULL CONSTRAINT PK_VND_ID PRIMARY KEY,
    VND_SCS_ID INTEGER NOT NULL,
    VND_NOMBRE VARCHAR2(50) NOT NULL,
    VND_DNI_EMPLEADO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_VND_SCS FOREIGN KEY(VND_SCS_ID) REFERENCES SUCURSALES(SCS_ID)
);

CREATE TABLE METODOS_PAGO(
    MTP_ID INTEGER NOT NULL CONSTRAINT PK_MTP_ID PRIMARY KEY,
    MTP_DESCRIPCION VARCHAR2(20)
);

CREATE TABLE VENTAS(
    VNT_ID INTEGER NOT NULL CONSTRAINT PK_VNT_ID PRIMARY KEY,
    VNT_CLI_ID INTEGER NOT NULL,
    VNT_VND_ID INTEGER NOT NULL,
    VNT_MTP_ID INTEGER NOT NULL,
    VNT_FECHA DATE NOT NULL,
    CONSTRAINT FK_VNT_CLI FOREIGN KEY(VNT_CLI_ID) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_VNT_VND FOREIGN KEY(VNT_VND_ID) REFERENCES VENDEDORES(VND_ID),
    CONSTRAINT FK_VNT_MTP FOREIGN KEY(VNT_MTP_ID) REFERENCES METODOS_PAGO(MTP_ID)
);

CREATE TABLE DETALLE_VENTAS(
    DTV_ID INTEGER NOT NULL CONSTRAINT PK_DTV_ID PRIMARY KEY,
    DTV_VNT_ID INTEGER NOT NULL,
    DTV_PRD_ID INTEGER NOT NULL,
    DTV_CANTIDAD INTEGER NOT NULL,
    DTV_PRECIO_APLICADO DECIMAL(20,2) NOT NULL,
    CONSTRAINT FK_DTV_VNT FOREIGN KEY(DTV_VNT_ID) REFERENCES VENTAS(VNT_ID),
    CONSTRAINT FK_DTV_PRD FOREIGN KEY(DTV_PRD_ID) REFERENCES PRODUCTOS(PRD_ID)
);








