--------------------------------------------------------------------------------
-- Esto se ejecuta con el usuario SYS.
--------------------------------------------------------------------------------
GRANT SELECT ON SISVENTAS_ER.CATEGORIAS TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.PRODUCTOS TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.CIUDADES TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.CLIENTES TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.SUCURSALES TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.VENDEDORES TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.METODOS_PAGO TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.VENTAS TO SISVENTAS_DW;
GRANT SELECT ON SISVENTAS_ER.DETALLE_VENTAS TO SISVENTAS_DW;
--------------------------------------------------------------------------------
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_CATEGORIAS TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_PRODUCTOS TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_CIUDADES TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_CLIENTES TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_SUCURSALES TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_VENDEDORES TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_METODOS_PAGO TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_VENTAS TO SISVENTAS_DW;
GRANT SELECT, INSERT ON SISVENTAS_SA.SA_DETALLE_VENTAS TO SISVENTAS_DW;
--------------------------------------------------------------------------------
