--------------------------------------------------------------------------------
-- Ejecutar con Usuario SISVENTAS_DW
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PG_ETL_SA AS
    PROCEDURE CARGA_CIUDADES;
    PROCEDURE CARGA_PRODUCTOS;
    PROCEDURE CARGA_SUCURSALES;
    PROCEDURE CARGA_CATEGORIAS;
    PROCEDURE CARGA_METODOS_PAGO;
    PROCEDURE CARGA_DATOS;
END PG_ETL_SA;
/
CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS

PROCEDURE CARGA_CIUDADES AS
BEGIN
INSERT INTO SISVENTAS_SA.SA_CIUDADES(CDD_ID, CDD_NOMBRE_CIUDAD)
SELECT CDD_ID, CDD_NOMBRE_CIUDAD
FROM SISVENTAS_ER.CIUDADES
WHERE CDD_ID NOT IN (SELECT CDD_ID FROM SISVENTAS_SA.SA_CIUDADES);
END CARGA_CIUDADES;


PROCEDURE CARGA_PRODUCTOS AS
BEGIN
INSERT INTO SISVENTAS_SA.SA_PRODUCTOS(PRD_ID, PRD_CTG_ID, PRD_NOMBRE_PRODUCTO, PRD_PRECIO_BASE)
SELECT PRD_ID, PRD_CTG_ID, PRD_NOMBRE_PRODUCTO, PRD_PRECIO_BASE
FROM SISVENTAS_ER.PRODUCTOS
WHERE PRD_ID NOT IN (SELECT PRD_ID FROM SISVENTAS_SA.SA_PRODUCTOS);
END CARGA_PRODUCTOS;


PROCEDURE CARGA_SUCURSALES AS
BEGIN
INSERT INTO SISVENTAS_SA.SA_SUCURSALES(SCS_ID, SCS_CDD_ID, SCS_NOMBRE_SUCURSAL)
SELECT SCS_ID, SCS_CDD_ID, SCS_NOMBRE_SUCURSAL
FROM SISVENTAS_ER.SUCURSALES
WHERE SCS_ID NOT IN (SELECT SCS_ID FROM SISVENTAS_SA.SA_SUCURSALES);
END CARGA_SUCURSALES;

    PROCEDURE CARGA_CATEGORIAS AS
    BEGIN
        INSERT INTO SISVENTAS_SA.SA_CATEGORIAS(CTG_ID, CTG_DESCRIPCION)
        SELECT CTG_ID, CTG_DESCRIPCION 
        FROM SISVENTAS_ER.CATEGORIAS
        WHERE CTG_ID NOT IN (SELECT CTG_ID FROM SISVENTAS_SA.SA_CATEGORIAS);
    END CARGA_CATEGORIAS;

    PROCEDURE CARGA_METODOS_PAGO AS
    BEGIN
        INSERT INTO SISVENTAS_SA.SA_METODOS_PAGO(MTP_ID, MTP_DESCRIPCION)
        SELECT MTP_ID, MTP_DESCRIPCION FROM SISVENTAS_ER.METODOS_PAGO
        WHERE MTP_ID NOT IN (SELECT MTP_ID FROM SISVENTAS_SA.SA_METODOS_PAGO);
    END CARGA_METODOS_PAGO;

PROCEDURE CARGA_DATOS AS
BEGIN
    CARGA_CIUDADES;
    CARGA_PRODUCTOS;
    CARGA_SUCURSALES;
    CARGA_CATEGORIAS;
    CARGA_METODOS_PAGO;
    COMMIT;
END CARGA_DATOS;

END PG_ETL_SA;
/
EXECUTE PG_ETL_SA.CARGA_DATOS;