--------------------------------------------------------------------------------
-- Creacion del Modelo Multidimensional.
-- Se conecta con el usuario creado para el modelo DW.
--------------------------------------------------------------------------------

CREATE TABLE DIM_METODOS_PAGO(
    MTP_ID INTEGER NOT NULL CONSTRAINT PK_MTP_ID PRIMARY KEY,
    MTP_DESCRIPCION VARCHAR2(20) NOT NULL
);

CREATE TABLE DIM_CATEGORIAS(
    CTG_ID INTEGER NOT NULL CONSTRAINT PK_CTG_ID PRIMARY KEY,
    CTG_DESCRIPCION VARCHAR2(30) NOT NULL
);

CREATE TABLE DIM_CIUDADES(
    CDD_ID INTEGER NOT NULL CONSTRAINT PK_CDD_ID PRIMARY KEY,
    CDD_NOMBRE_CIUDAD VARCHAR2(50) NOT NULL
);

CREATE TABLE DIM_CLIENTES(
    CLI_ID INTEGER NOT NULL CONSTRAINT PK_CLI_ID PRIMARY KEY,
    CLI_NOMBRE VARCHAR2(100) NOT NULL,
    CLI_APELLIDO VARCHAR2(100) NOT NULL,
    CLI_CONTACTO VARCHAR2(50) NOT NULL
);

CREATE TABLE DIM_PRODUCTOS(
    PRD_ID INTEGER NOT NULL CONSTRAINT PK_PRD_ID PRIMARY KEY,
    PRD_NOMBRE_PRODUCTO VARCHAR2(50) NOT NULL
);

CREATE TABLE DIM_SUCURSALES(
    SCS_ID INTEGER NOT NULL CONSTRAINT PK_SCS_ID PRIMARY KEY,
    SCS_NOMBRE_SUCURSAL VARCHAR2(30) NOT NULL
);

CREATE TABLE DIM_VENDEDORES(
    VND_ID INTEGER NOT NULL CONSTRAINT PK_VND_ID PRIMARY KEY,
    VND_NOMBRE VARCHAR2(50) NOT NULL,
    VND_DNI_EMPLEADO VARCHAR2(20) NOT NULL
);

CREATE TABLE DIM_FECHA(
    FEC_ID INTEGER NOT NULL CONSTRAINT PK_FEC_ID PRIMARY KEY,
    FEC_FECHA DATE NOT NULL
);

CREATE TABLE FACT_VENTAS(
    VNT_MTP_ID INTEGER NOT NULL,
    VNT_CTG_ID INTEGER NOT NULL,
    VNT_CDD_ID INTEGER NOT NULL,
    VNT_CLI_ID INTEGER NOT NULL,
    VNT_PRD_ID INTEGER NOT NULL,
    VNT_SCS_ID INTEGER NOT NULL,
    VNT_VND_ID INTEGER NOT NULL,
    VNT_FEC_ID INTEGER NOT NULL,
    CONSTRAINT PK_VNT PRIMARY KEY(VNT_MTP_ID, VNT_CTG_ID, VNT_CDD_ID, VNT_CLI_ID, VNT_PRD_ID, VNT_SCS_ID, VNT_VND_ID, VNT_FEC_ID),
    CONSTRAINT FK_VNT_MTP FOREIGN KEY(VNT_MTP_ID) REFERENCES DIM_METODOS_PAGO(MTP_ID),
    CONSTRAINT FK_VNT_CTG FOREIGN KEY(VNT_CTG_ID) REFERENCES DIM_CATEGORIAS(CTG_ID),
    CONSTRAINT FK_VNT_CDD FOREIGN KEY(VNT_CDD_ID) REFERENCES DIM_CIUDADES(CDD_ID),
    CONSTRAINT FK_VNT_CLI FOREIGN KEY(VNT_CLI_ID) REFERENCES DIM_CLIENTES(CLI_ID),
    CONSTRAINT FK_VNT_PRD FOREIGN KEY(VNT_PRD_ID) REFERENCES DIM_PRODUCTOS(PRD_ID),
    CONSTRAINT FK_VNT_SCS FOREIGN KEY(VNT_SCS_ID) REFERENCES DIM_SUCURSALES(SCS_ID),
    CONSTRAINT FK_VNT_VND FOREIGN KEY(VNT_VND_ID) REFERENCES DIM_VENDEDORES(VND_ID),
    CONSTRAINT FK_VNT_FEC FOREIGN KEY(VNT_FEC_ID) REFERENCES DIM_FECHA(FEC_ID)
);






