--------------------------------------------------------------------------------
-- CREACION DE TABLAS STAGING AREA.
-- SE CONECTA CON EL USUARIO CREADO PARA SA.
--------------------------------------------------------------------------------

CREATE TABLE SA_CATEGORIAS(
    CTG_ID VARCHAR2(255),
    CTG_DESCRIPCION VARCHAR2(255)
);

CREATE TABLE SA_PRODUCTOS(
    PRD_ID VARCHAR2(255),
    PRD_CTG_ID VARCHAR2(255),
    PRD_NOMBRE_PRODUCTO VARCHAR2(255),
    PRD_PRECIO_BASE VARCHAR2(255)
);

CREATE TABLE SA_CIUDADES(
    CDD_ID VARCHAR2(255),
    CDD_NOMBRE_CIUDAD VARCHAR2(255)
);

CREATE TABLE SA_CLIENTES(
    CLI_ID VARCHAR2(255),
    CLI_CDD_ID VARCHAR2(255),
    CLI_NOMBRE VARCHAR2(255),
    CLI_APELLIDO VARCHAR2(255),
    CLI_CONTACTO VARCHAR2(255)
);

CREATE TABLE SA_SUCURSALES(
    SCS_ID VARCHAR2(255),
    SCS_CDD_ID VARCHAR2(255),
    SCS_NOMBRE_SUCURSAL VARCHAR2(255)
);

CREATE TABLE SA_VENDEDORES(
    VND_ID VARCHAR2(255),
    VND_SCS_ID VARCHAR2(255),
    VND_NOMBRE VARCHAR2(255),
    VND_DNI_EMPLEADO VARCHAR2(255)
);

CREATE TABLE SA_METODOS_PAGO(
    MTP_ID VARCHAR2(255),
    MTP_DESCRIPCION VARCHAR2(255)
);

CREATE TABLE SA_VENTAS(
    VNT_ID VARCHAR2(255),
    VNT_CLI_ID VARCHAR2(255),
    VNT_VND_ID VARCHAR2(255),
    VNT_MTP_ID VARCHAR2(255),
    VNT_FECHA VARCHAR2(255)
);

CREATE TABLE SA_DETALLE_VENTAS(
    DTV_ID VARCHAR2(255),
    DTV_VNT_ID VARCHAR2(255),
    DTV_PRD_ID VARCHAR2(255),
    DTV_CANTIDAD VARCHAR2(255),
    DTV_PRECIO_APLICADO VARCHAR2(255)
);
