SELECT 
       CODIGO_TRANSACCION,
       CODIGO_CLIENTE,
       MONTO_AHORRO,
       MONTO_PRESTAMO,
       MONTO_INVERSION,
       FECHA_TRANSACCION,
       TOTAL_INVERSION_CTE,
       TOTAL_PRETAMO_CTE,
       TOTAL_AHORRO_CTE,
       PRIMER_PRESTAMO_CTE,
       ULTIMO_PRESTAMO_CTE,
       SIGUIENTE_PRESTAMO_CTE,
       ANTERIOR_PRESTAMO_CTE,
       PORCENTAJE_TOTAL_AHORRO_CTE,
       PORCENTAJE_TOTAL_INVERSION_CTE,
       PORCENTAJE_TOTAL_PRESTAMO_CTE,
       MONTO_TOTAL_TRANSACCION_CTE,
       RANKING_MONTO_INVERSION,
       RANKING_DENSO_MONTO_INVERSION
FROM (
    SELECT 
           CODIGO_TRANSACCION,
           CODIGO_CLIENTE,
           FECHA_TRANSACCION,
           MONTO_AHORRO,
           MONTO_PRESTAMO,
           MONTO_INVERSION,
           SUM(MONTO_INVERSION) OVER(PARTITION BY CODIGO_CLIENTE) TOTAL_INVERSION_CTE,
           SUM(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE) TOTAL_PRETAMO_CTE,
           SUM(MONTO_AHORRO) OVER(PARTITION BY CODIGO_CLIENTE) TOTAL_AHORRO_CTE,
           FIRST_VALUE(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE ORDER BY FECHA_TRANSACCION) PRIMER_PRESTAMO_CTE,
           LAST_VALUE(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE ORDER BY FECHA_TRANSACCION 
           ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) ULTIMO_PRESTAMO_CTE,
           LEAD(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE ORDER BY FECHA_TRANSACCION) SIGUIENTE_PRESTAMO_CTE,
           LAG(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE ORDER BY FECHA_TRANSACCION) ANTERIOR_PRESTAMO_CTE,
           ROUND(SUM(MONTO_AHORRO) OVER(PARTITION BY CODIGO_CLIENTE) / NULLIF(SUM(MONTO_AHORRO) OVER(), 0) * 100 , 2) PORCENTAJE_TOTAL_AHORRO_CTE,
           ROUND(SUM(MONTO_INVERSION) OVER(PARTITION BY CODIGO_CLIENTE) / NULLIF(SUM(MONTO_INVERSION) OVER(), 0) * 100 , 2) PORCENTAJE_TOTAL_INVERSION_CTE,
           ROUND(SUM(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE) / NULLIF(SUM(MONTO_PRESTAMO) OVER(), 0) * 100 , 2) PORCENTAJE_TOTAL_PRESTAMO_CTE,
           (SUM(MONTO_INVERSION) OVER(PARTITION BY CODIGO_CLIENTE) + SUM(MONTO_PRESTAMO) OVER(PARTITION BY CODIGO_CLIENTE) + 
            SUM(MONTO_AHORRO) OVER(PARTITION BY CODIGO_CLIENTE)) MONTO_TOTAL_TRANSACCION_CTE,
           RANK() OVER(ORDER BY MONTO_INVERSION DESC) RANKING_MONTO_INVERSION,
           DENSE_RANK() OVER(ORDER BY MONTO_INVERSION DESC) RANKING_DENSO_MONTO_INVERSION
    FROM (
        SELECT
               CODIGO_TRANSACCION,
               CODIGO_CLIENTE,
               TIPO_TRANSACCION,
               MONTO,
               FECHA FECHA_TRANSACCION
        FROM TRANSACCIONES_FINANCIERAS
        WHERE TIPO_TRANSACCION != 'Aventura'
    )
    PIVOT (
           SUM(MONTO)
           FOR TIPO_TRANSACCION IN (
               'Ahorro' AS MONTO_AHORRO,
               'Prestamo' AS MONTO_PRESTAMO,
               'Inversion' AS MONTO_INVERSION
           )
    )
) ORDER BY CODIGO_CLIENTE, FECHA_TRANSACCION;