CREATE TABLE EX_CLIENTE (
    CTE_ID        INTEGER PRIMARY KEY NOT NULL,
    CTE_NOMBRE    VARCHAR2(100) NOT NULL,
    CTE_DIRECCION VARCHAR2(255) NOT NULL,
    CTE_LIMITE_CREDITO DECIMAL(20,2) NOT NULL
);

CREATE TABLE EX_PRESTAMO (
    PST_ID     INTEGER PRIMARY KEY NOT NULL,
    PST_CTE_ID INTEGER NOT NULL,
    PST_MONTO  DECIMAL(10,2) NOT NULL,
    PST_TASA_INTERES DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (PST_CTE_ID) REFERENCES EX_CLIENTE(CTE_ID)
);

-- Inserts para la tabla EX_CLIENTE
INSERT INTO EX_CLIENTE (CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO) VALUES (1, 'Juan Perez', 'Calle 123, Ciudad', 5000.00);
INSERT INTO EX_CLIENTE (CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO) VALUES (2, 'Maria Lopez', 'Avenida Principal, Pueblo', 7000.00);
INSERT INTO EX_CLIENTE (CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO) VALUES (3, 'Carlos Garcia', 'Av. Libertad, Colonia', 10000.00);
INSERT INTO EX_CLIENTE (CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO) VALUES (4, 'Laura Martinez', 'Rue de la Paix, Paris', 15000.00);
INSERT INTO EX_CLIENTE (CTE_ID, CTE_NOMBRE, CTE_DIRECCION, CTE_LIMITE_CREDITO) VALUES (5, 'Pedro Rodriguez', '123 Elm Street, Springfield', 20000.00);

-- Inserts para la tabla EX_PRESTAMO
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (1, 1, 3000.00, 8.5);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (2, 2, 5000.00, 7.0);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (3, 3, 8000.00, 6.5);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (4, 4, 10000.00, 6.0);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (5, 5, 12000.00, 5.5);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (6, 1, 7000.00, 7.5);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (7, 2, 9000.00, 6.0);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (8, 3, 11000.00, 5.0);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (9, 4, 13000.00, 4.5);
INSERT INTO EX_PRESTAMO (PST_ID, PST_CTE_ID, PST_MONTO, PST_TASA_INTERES) VALUES (10, 5, 15000.00, 4.0);

COMMIT;